/* 
    получаем таблицу дополнительных часов
 */
let
    source = #"_присоединяем_схему", //ссылка на предыдущий шаг
    filter_out_1k1n = Table.SelectRows(source, //исключаем классификаторы 1к, 1н
        each ([классификатор_key] <> "1к") and ([классификатор_key] <> "1н")
    )
in
    filter_out_1k1n