let
    source = #"_типовые_объединение", 
    check_pk = fnCheckPrimaryKey(source, [column = "типовые_key", file_name = "справочник google", table_name = "типовые"]),
    add_sort = fnAddSort(
        check_pk, 
        [
            columns = {
                "типовые ур0 наименование", 
                "типовые ур1 наименование",
                "типовые ур2 наименование",
                "типовые ур3 наименование",
                "типовые ур4 наименование",
                "типовые ур0 наименование с ед изм",
                "типовые ур1 наименование с ед изм",
                "типовые ур2 наименование с ед изм",
                "типовые ур3 наименование с ед изм",
                "типовые ур4 наименование с ед изм"
            }
        ]
    ),
    add_slicers = 
        let
            add_lvl0_unit_slicer = Table.AddColumn(add_sort, "типовые ур0 наименование срез", each [типовые ур0 наименование]),
            add_lvl1_unit_slicer = Table.AddColumn(add_lvl0_unit_slicer, "типовые ур1 наименование срез", each [типовые ур1 наименование]),
            add_lvl2_unit_slicer = Table.AddColumn(add_lvl1_unit_slicer, "типовые ур2 наименование срез", each [типовые ур2 наименование]),
            add_lvl3_unit_slicer = Table.AddColumn(add_lvl2_unit_slicer, "типовые ур3 наименование срез", each [типовые ур3 наименование]),
            add_lvl4_unit_slicer = Table.AddColumn(add_lvl3_unit_slicer, "типовые ур4 наименование срез", each [типовые ур4 наименование]),
            add_lvl0_unit_with_descr_slicer = Table.AddColumn(add_lvl4_unit_slicer, "типовые ур0 наименование с ед изм срез", each [типовые ур0 наименование с ед изм]),
            add_lvl1_unit_with_descr_slicer = Table.AddColumn(add_lvl0_unit_with_descr_slicer, "типовые ур1 наименование с ед изм срез", each [типовые ур1 наименование с ед изм]),
            add_lvl2_unit_with_descr_slicer = Table.AddColumn(add_lvl1_unit_with_descr_slicer, "типовые ур2 наименование с ед изм срез", each [типовые ур2 наименование с ед изм]),
            add_lvl3_unit_with_descr_slicer = Table.AddColumn(add_lvl2_unit_with_descr_slicer, "типовые ур3 наименование с ед изм срез", each [типовые ур3 наименование с ед изм]),
            add_lvl4_unit_with_descr_slicer = Table.AddColumn(add_lvl3_unit_with_descr_slicer, "типовые ур4 наименование с ед изм срез", each [типовые ур4 наименование с ед изм])
        in
            add_lvl4_unit_with_descr_slicer,
    add_refresh_datetime = fnAddRefreshDateTime(add_slicers, [column = "время обновления google"]),
    select_columns = Table.SelectColumns(
        add_refresh_datetime,
        {
            "типовые_key",
            "типовые",
            "ед изм",
            "типовые вид работ",
            "добавлено гувр",
            "типовые уровень",
            "типовые ур глубина",
            "типовые наименование",
            "типовые наименование с ед изм",
            "типовые наименование с ед изм и кодом",
            "типовые ур0 наименование",
            "типовые ур0 наименование с ед изм",
            "типовые ур0 наименование с ед изм и кодом",
            "типовые ур0 вед поз",
            "типовые ур1 наименование",
            "типовые ур1 наименование с ед изм",
            "типовые ур1 наименование с ед изм и кодом",
            "типовые ур1 вед поз",
            "типовые ур2 наименование",
            "типовые ур2 наименование с ед изм",
            "типовые ур2 наименование с ед изм и кодом",
            "типовые ур2 вед поз",
            "типовые ур3 наименование",
            "типовые ур3 наименование с ед изм",
            "типовые ур3 наименование с ед изм и кодом",
            "типовые ур3 вед поз",
            "типовые ур4 наименование",
            "типовые ур4 наименование с ед изм",
            "типовые ур4 наименование с ед изм и кодом",
            "типовые ур4 вед поз",
            "типовые ур0 наименование_sort",
            "типовые ур1 наименование_sort",
            "типовые ур2 наименование_sort",
            "типовые ур3 наименование_sort",
            "типовые ур4 наименование_sort",
            "типовые ур0 наименование с ед изм_sort",
            "типовые ур1 наименование с ед изм_sort",
            "типовые ур2 наименование с ед изм_sort",
            "типовые ур3 наименование с ед изм_sort",
            "типовые ур4 наименование с ед изм_sort",
            "типовые ур0 наименование срез",
            "типовые ур1 наименование срез",
            "типовые ур2 наименование срез",
            "типовые ур3 наименование срез",
            "типовые ур4 наименование срез",
            "типовые ур0 наименование с ед изм срез",
            "типовые ур1 наименование с ед изм срез",
            "типовые ур2 наименование с ед изм срез",
            "типовые ур3 наименование с ед изм срез",
            "типовые ур4 наименование с ед изм срез",
            "время обновления google"
        }
    )
in
    select_columns