/* 
    получаем список организаций для переименования
 */
let
    source = #"нормализация", //ссылка на шаг с таблицей в которой заданы значения нормализации
    filter_data = Table.SelectRows(source, each ([имя столбца] = "организация")), //оставляем строки для организации
    select_mapping = Table.SelectColumns(filter_data,{"значение исходное", "значение результат"}), //оставляем таблицу со значениями, которые мы ищем и результирующими
    to_rows = Table.ToRows(select_mapping), //создаем список из списков найти - заменить
    buffer = List.Buffer(to_rows) //в буфер для ускорения времени работы
in
    buffer