/*
    из файла схема загружаем таблицу "ключевые"
 */
let
    source = fnGetTableFromFile(#"схема_путь", [kind = "Table", name = "ключевые"]), //загружаем таблицу ключевые
    select_cols = Table.SelectColumns( //выбираем нужные поля
        source, 
        {
            "ключевые_key",
            "типовые_key",
            "типовые вед поз",
            "ключевые наименование",
            "ед изм",
            "ключевые наименование с ед изм",
            "ключевые уровень",
            "ключевые уровень глубина",
            "ключевые вед поз",
            "ключевые ур0 наименование",
            "ключевые ур0 наименование с ед изм",
            "ключевые ур0 вед поз",
            "ключевые ур1 наименование",
            "ключевые ур1 наименование с ед изм",
            "ключевые ур1 вед поз",
            "ключевые ур0 наименование_sort",
            "ключевые ур1 наименование_sort",
            "ключевые ур0 наименование с ед изм_sort",
            "ключевые ур1 наименование с ед изм_sort",
            "ключевые ур0 наименование срез",
            "ключевые ур1 наименование срез",
            "ключевые ур0 наименование с ед изм срез",
            "ключевые ур1 наименование с ед изм срез"
        }
    )
in
    select_cols