/* 
    из файла схема загружаем таблицу "организация"
 */
let
    source = #"_содержимое_схемы"{[Item="организация",Kind="Table"]}[Data], //загружаем таблицу организация
    select_cols = Table.SelectColumns( //выбираем нужные поля
        source, 
        {
            "организация_key",
            "организация",
            "организация_sort"
        }
    ) 
in
    select_cols