/* 
    из файла схема загружаем таблицу с "типовые"
 */
let
    source = #"_содержимое_схемы"{[Item="типовые",Kind="Table"]}[Data], //загружаем таблицу типовые
    select_cols = Table.SelectColumns( //выбираем нужные поля
        source, 
            {
                "типовые_key",
                "типовые",
                "ед изм",
                "типовые ур глубина",
                "типовые наименование",
                "типовые наименование с ед изм",
                "типовые наименование с ед изм и кодом",
                "типовые ур0 наименование",
                "типовые ур0 наименование с ед изм",
                "типовые ур0 наименование с ед изм и кодом",
                "типовые ур0 вед поз",
                "типовые ур1 наименование",
                "типовые ур1 наименование с ед изм",
                "типовые ур1 наименование с ед изм и кодом",
                "типовые ур1 вед поз",
                "типовые ур2 наименование",
                "типовые ур2 наименование с ед изм",
                "типовые ур2 наименование с ед изм и кодом",
                "типовые ур2 вед поз",
                "типовые ур3 наименование",
                "типовые ур3 наименование с ед изм",
                "типовые ур3 наименование с ед изм и кодом",
                "типовые ур3 вед поз",
                "типовые ур4 наименование",
                "типовые ур4 наименование с ед изм",
                "типовые ур4 наименование с ед изм и кодом",
                "типовые ур4 вед поз",
                "типовые ур0 наименование_sort",
                "типовые ур1 наименование_sort",
                "типовые ур2 наименование_sort",
                "типовые ур3 наименование_sort",
                "типовые ур4 наименование_sort",
                "типовые ур0 наименование с ед изм_sort",
                "типовые ур1 наименование с ед изм_sort",
                "типовые ур2 наименование с ед изм_sort",
                "типовые ур3 наименование с ед изм_sort",
                "типовые ур4 наименование с ед изм_sort",
                "время обновления google"
            }
    ),
    change_dtype = Table.TransformColumnTypes( //изменяем тип данных
        select_cols,
        {
            {"типовые_key", type text},
            {"типовые", type text},
            {"ед изм", type text},
            {"типовые ур глубина", type number},
            {"типовые наименование", type text},
            {"типовые наименование с ед изм", type text},
            {"типовые наименование с ед изм и кодом", type text},
            {"типовые ур0 наименование", type text},
            {"типовые ур0 наименование с ед изм", type text},
            {"типовые ур0 наименование с ед изм и кодом", type text},
            {"типовые ур0 вед поз", type text},
            {"типовые ур1 наименование", type text},
            {"типовые ур1 наименование с ед изм", type text},
            {"типовые ур1 наименование с ед изм и кодом", type text},
            {"типовые ур1 вед поз", type text},
            {"типовые ур2 наименование", type text},
            {"типовые ур2 наименование с ед изм", type text},
            {"типовые ур2 наименование с ед изм и кодом", type text},
            {"типовые ур2 вед поз", type text},
            {"типовые ур3 наименование", type text},
            {"типовые ур3 наименование с ед изм", type text},
            {"типовые ур3 наименование с ед изм и кодом", type text},
            {"типовые ур3 вед поз", type text},
            {"типовые ур4 наименование", type text},
            {"типовые ур4 наименование с ед изм", type text},
            {"типовые ур4 наименование с ед изм и кодом", type text},
            {"типовые ур4 вед поз", type text},
            {"типовые ур0 наименование_sort", type number},
            {"типовые ур1 наименование_sort", type number},
            {"типовые ур2 наименование_sort", type number},
            {"типовые ур3 наименование_sort", type number},
            {"типовые ур4 наименование_sort", type number},
            {"типовые ур0 наименование с ед изм_sort", type number},
            {"типовые ур1 наименование с ед изм_sort", type number},
            {"типовые ур2 наименование с ед изм_sort", type number},
            {"типовые ур3 наименование с ед изм_sort", type number},
            {"типовые ур4 наименование с ед изм_sort", type number}
        }
    )
in
    change_dtype